### ISSUE TITLE
Module: tsvsf - Does not normalize paths

### ISSUE THREAD

**Issue by kevinramharak** [microsoft/TypeScript-Website#1680]
As reported in https://github.com/microsoft/TypeScript-Website/issues/1669#issuecomment-799378345 the `@typescript/vfs` package tests will fail on Windows because of path seperator issues.

The code at https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescript-vfs/test/fsbacked.test.ts#L43-L46

Will produce [different results](https://nodejs.org/api/path.html#path_windows_vs_posix) depending on the operating system and its path seperator. A bandaid fix would be to use `path.posix` in the tests to force `/` to be used as seperator.

Looking at the compiler it states in https://github.com/microsoft/TypeScript/blob/master/src/compiler/path.ts#L3-L7 that internally `/` is used, but it expects the `CompilerHost | LanguageServiceHost` to 'correctly handle paths in our specified format'. Im not sure what means, but I understand it as the host object being responsible for using the internal used seperator. If so I would suggest patching `@typescript/vfs` to normalize the paths on input.

If you agree I'll take a look in how the compiler implements its hosts and see where `vfs` needs to be patched to behave similar.

**Comment by hahmadia** [comment]
Having a quick look at the Typescript compiler, this seems to be the function they use to normalize the seperators.
https://github.com/microsoft/TypeScript/blob/322c70fd8259b2beef001e1a346fc75ab070dbea/src/compiler/path.ts#L454

I think you can create a PR to solve this by patching the FSFileBackedSystem function.
I believe the only change you'll need to make is 
```ts
  const root = ts.normalizeSlashes(_projectRoot + "/vfs")
```
Use the typescript normalize slash function and it should fix the issues you are coming across. Try it out and let me know.

**Comment by kevinramharak** [comment]
What about the entries in the `Map<string, string>` that is passed to `createSystem`. And the `System` & `CompilerHost` objects that `vfs` creates with their own API's to manipulate files? From what I can tell using any javascript code (including the `path` module) that uses windows seperator will create unsafe paths to pass to `vfs`. Since the compiler expects that the `Host` object knows of this internal requirement and feeds it normalized paths only.

I'm also wondering how to treat `ts.normalizeSlashes` since its an `@internal` function. Should we just rely on it being present, or copy it to have the implementation local.

**Comment by hahmadia** [comment]
In the same `compiler/path.ts` file, you can see typescript normalizes `\\` to `/` throughout the code. 
I've created a PR bring in the implementation of normalizeSlashes into the index.ts file. 
I don't have access to a windows computer but do you mind trying my changes locally and let me know if it resolves the problem for you https://github.com/microsoft/TypeScript-Website/pull/1681 ? 
All we are really doing here is replacing `\\` with `/` in your path.

**Comment by kevinramharak** [comment]
I understand your proposed fix, but you seem to be missing what im trying to pointout. `System` and `CompilerHost` have API's to allow the compiler to interact with its host environment.

The test I mentioned does the following:
```ts
  const monorepoRoot = path.join(__dirname, "..", "..", "..")
  const fakeFolder = path.join(monorepoRoot, "fake")
  const exporter = path.join(fakeFolder, "file-with-export.ts")
  const index = path.join(fakeFolder, "index.ts")

  fsMap.set(exporter, `export const helloWorld = "Example string";`)
  fsMap.set(index, `import {helloWorld} from "./file-with-export"; console.log(helloWorld)`)

  const system = createFSBackedSystem(fsMap, monorepoRoot, ts)
  const env = createVirtualTypeScriptEnvironment(system, [index, exporter], ts, compilerOpts)
  ```
  
  On a windows system this results in `fsMap` looking like this:
  ```
  0:(2) ['C:\\Users\\kevin\\Documents\\Projects\\TypeScript-Website\\fake\\file-with-export.ts', 'export const helloWorld = "Example string";']
1:(2) ['C:\\Users\\kevin\\Documents\\Projects\\TypeScript-Website\\fake\\index.ts', 'import {helloWorld} from "./file-with-export"; console.log(helloWorld)']
  ```

My point is that `vfs` blindly accepts this as valid filepaths, while the compiler expects those paths to be normalized. This is the reason the import of `./file-with-export` fails. It asks the host for a path with `/` slashes, but since `vfs` never normalized those paths it will respond with `undefined` stating that file does not exist.

The proposed fix isn't to normalize one input, but to guard all entry points. The comment in `path.ts` pointed out that this is the responsibility of the `CompilerHost` object.

**Comment by hahmadia** [comment]
Okay sorry I think now I understood your meaning. In that case, I pushed a change where we normalize the files we are passing in before dealing with them. So we normalize both the root and file paths given. Does that handle the problem? Do you mind giving it a try?

**Comment by kevinramharak** [comment]
It is a step in the right direction but I feel this isn't solving the problem at its core. I'd rather have `vfs` behave exactly as the rest of the compiler would expect it to, than patch bugs when they arise. This would save headaches in the future as I think the package is a great corner stone to be reused in all kinds of tooling.

**Comment by kevinramharak** [comment]
Looking at the test harness this is an interesting file:
https://github.com/microsoft/TypeScript/blob/902fcb0cc749362f92dac48a29fb50fcf32c09a9/src/harness/vfsUtil.ts
But that seems overkill.

**Comment by hahmadia** [comment]
@kevinramharak

Ok I fixed that test case. You can try my PR now. Basically I normalize all the user given paths (passed through parameters). It normalizes the FSMap you pass it in. Try it now. It's simple and solves the problem I believe.

**Comment by hahmadia** [comment]
I tried it on my local windows computer and the test case that was initially failing now passes.

**Comment by kevinramharak** [comment]
@hahmadia I appreciate the effort, and it indeed fixes the test, but IMO it does not fix the underlying problem. Im mostly interested in a discussion what the proper fix would be before applying any patches.

I could easily add another test case and have it break again, I'm not looking to fix the tests. I'd like to tackle the problem.

**Comment by hahmadia** [comment]
@kevinramharak Ya no worries but I'm sad I can't seem to grasp what the underlying issue is.

My understanding was that VFS doesn't normalize it's paths but I guess it's beyond just that. 

Any chance you can provide more test case examples to see maybe if I can grasp what you mean?

@orta Any input on your end?

**Comment by kevinramharak** [comment]
I would be happy to try and explain what I think is happening.

The compiler is a huge project and has modular parts that all have their own role. These parts can be connected to each other to form a pipeline. The pipeline is what takes your project as an input and then spits out javascript as output. The typescript compiler itself is focussed on having each part be able to its own thing very well and thus you can easily take a small part of the compiler and as long as your input fits it will produce the correct output.

The parts `vfs` is touching is a very 'bottom' layer of this pipeline. The compiler defines two interfaces `System` and `CompilerHost` (there are other variants, but we will ignore them for now). `System` is defined here https://github.com/microsoft/TypeScript/blob/322c70fd8259b2beef001e1a346fc75ab070dbea/src/compiler/sys.ts#L1159. 

`System` is an interface that abstracts the OS filesystem. This way the rest of the codebase only talks with this interface and the implementation will take care of the annoying details.

The `CompilerHost` is defined here https://github.com/microsoft/TypeScript/blob/716b167f2b19e1642bd65aba33400afe8c181889/src/compiler/types.ts#L6369.

The `CompilerHost` is another abstraction that sits on top of the `System`. If you compare the interfaces you see that this object knows more about the compiler and its types than `System`. It knows how to create `SourceFile`'s and exposes functions to resolve module names like `import ts from 'typescript'` and reports where the actual files can be found on disk (and thus they can be converted into `SourceFile`'s themselfs).

This sort of gives us this mental model:
```
-----------------
|  TS Compiler |
---------------------
| ts.CompilerHost |
-------------
| ts.System |
-------
| path | // see https://nodejs.org/api/path.html
------
| NodeJS   |
-------
| OS  |
-------
```

As you can see from my awesome illustration the rest of the compiler only interfaces with the `CompilerHost` object.  
The comment inside the `path.ts` file tells me that every line of code inside `TS Compiler` is convinced directories in paths are always seperated by `/` characters.

So it is up to the `CompilerHost` to hide to the rest of the compiler that a Windows system has `\` seperators. What I think `vfs` is missing is this behaviour. And this is why the file `./file-with-export.ts` cannot be found. Because the `CompilerHost` should hide from the rest of the compiler that the actual path is `.\file-with-export.ts`.

I hope this helps. I'm hoping to add to https://github.com/orta/typescript-notes soon enough where this info will be clearly explained.

**Comment by kevinramharak** [comment]
@hahmadia Based on your [PR](https://github.com/microsoft/TypeScript-Website/pull/1681/files) I implemented [this PR](https://github.com/microsoft/TypeScript-Website/pull/1699).
